apiVersion: v1
kind: Namespace
metadata:
  name: backend
  labels:
    chaos-injection: "enabled"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: chaos-plan-info
  namespace: backend
data:
  note: "Label workload with chaos-target=true to be selected by chaos experiments"
  duration: "24h"
