apiVersion: chaos-mesh.org/v1alpha1
kind: NetworkChaos
metadata:
  name: net-duplicate
  namespace: backend
spec:
  action: duplicate
  mode: fixed-percent
  value: "60"
  selector:
    namespaces:
      - backend
    labelSelectors:
      chaos-target: "true"
  duplicate:
    duplicate: "8"
    correlation: "20"
  duration: "20m"
