apiVersion: chaos-mesh.org/v1alpha1
kind: DNSChaos
metadata:
  name: dns-random-error
  namespace: backend
spec:
  action: error
  mode: all
  selector:
    namespaces:
      - backend
    labelSelectors:
      chaos-target: "true"
  patterns:
    - "*.svc.cluster.local"
  duration: "20m"
---
apiVersion: chaos-mesh.org/v1alpha1
kind: DNSChaos
metadata:
  name: dns-timeout-sim
  namespace: backend
spec:
  action: random
  mode: fixed-percent
  value: "70"
  selector:
    namespaces:
      - backend
    labelSelectors:
      chaos-target: "true"
  patterns:
    - "kubernetes.default.svc.cluster.local"
    - "*.backend.svc.cluster.local"
  duration: "20m"
